name: SpongeRestore
main: pgDev.bukkit.SpongeRestore.SpongeRestore
version: 1.5
author: PG Dev Team
authors: [Devil Boy]
description: Bringing back the functionality of sponges.

commands:
   sponge:
      description: Enable or disable sponges!
      usage: /<command> <enable/disable/clear>
   sponges:
      description: Alternative to "sponge" command.
      usage: /<command> <enable/disable/clear>
   sr:
      description: Alternative to "sponge" command.
      usage: /<command> <enable/disable/clear>

permissions:
    spongerestore.*:
        default: op
        description: Gives access to all sponge database editing commands.
        children:
            spongerestore.enable: true
            spongerestore.disable: true
            spongerestore.clear: true
    spongerestore.enable:
        default: op
        description: Can use the "/sponge enable" command.
        command: "/sponge enable <target/radius/selection> [#]"
    spongerestore.disable:
        default: op
        description: Can use the "/sponge disable" command.
        command: "/sponge disable <target/radius/selection> [#]"
    spongerestore.clear:
        default: op
        description: Can use the "/sponge clear" command.
        command: "/sponge clear"
    spongerestore.clear.all:
        default: op
        description: Can clear the whole sponge database.
        command: "/sponge clear all"