name: SpongeRestore
main: DevilBoy.SpongeRestore.SpongeRestore
version: 1.0
author: Devil Boy
description: Bringing back the functionality of sponges.
website: http://forums.bukkit.org/threads/fun-mech-spongerestore-v0-9-5-bring-back-the-functionality-of-sponges-766-803.18204/

commands:
   sponge:
      description: Enable or disable sponges!
      usage: /<command> <enable/disable/clear>
   sponges:
      description: Alternative to "sponge" command.
      usage: /<command> <enable/disable/clear>
   sr:
      description: Alternative to "sponge" command.
      usage: /<command> <enable/disable/clear>